### ISSUE TITLE
Prepare for showing site to warbo

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedMain#9]
We are still only doing html(and dummy data if anything), but here is what we need before we are done:
- Some way of displaying pages that can have different "cells" of content
- Clean front page
- Decent navigation

Are we ready to show it to warbo?

**Comment by exeron** [comment]
Well, there is still some small css bugs.. just found one. 
The whole site is not ready for a evaluation, but the main question is the design/layout.
Since I separated the css and css-coloring it should also be possible to change the theme with ease.
Example: Give the LAN a theme like pac-man. Set coloring in color.css and change the images in images folder, and Done! :)

**Comment by halvors** [comment]
@petterroea @brageskj This issue seems to have solved itself :O
